
import { Subject, Task, Achievement } from './types';

export const TASKS: Task[] = [
  { id: 'revision', label: 'রিভিশন শেষ' },
  { id: 'medical_class', label: 'মেডিকেল ক্লাস' },
  { id: 'practice', label: 'প্র্যাকটিস এবং অনুশীলনী' },
  { id: 'question_bank', label: 'মেডিকেল প্রশ্নব্যাংক' },
];

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_step',
    title: 'প্রথম পদক্ষেপ',
    description: 'অন্তত ১টি টাস্ক সম্পন্ন করেছেন',
    icon: 'Footprints',
    color: '#10b981'
  },
  {
    id: 'first_chapter',
    title: 'অধ্যায় জয়ী',
    description: '১টি সম্পূর্ণ অধ্যায় শেষ করেছেন',
    icon: 'Trophy',
    color: '#f59e0b'
  },
  {
    id: 'halfway_hero',
    title: 'অর্ধেক পথ',
    description: 'সম্পূর্ণ সিলেবাসের ৫০% শেষ করেছেন',
    icon: 'Medal',
    color: '#8b5cf6'
  },
  {
    id: 'subject_master',
    title: 'বিষয় বিশেষজ্ঞ',
    description: 'যেকোনো ১টি বিষয় ১০০% শেষ করেছেন',
    icon: 'Crown',
    color: '#ef4444'
  },
  {
    id: 'weekly_warrior',
    title: 'সাপ্তাহিক যোদ্ধা',
    description: 'টানা ৭ দিন পড়াশোনা করেছেন',
    icon: 'Flame',
    color: '#f97316'
  },
  {
    id: 'mat_ready',
    title: 'ভর্তি যুদ্ধে প্রস্তুত',
    description: '১০০% প্রস্তুতি সম্পন্ন করেছেন',
    icon: 'Stethoscope',
    color: '#0ea5e9'
  }
];

export const MOTIVATIONAL_LINES = [
  { bn: "প্রতিদিন একটু করে এগো, বড় সাফল্য আসবে।", en: "Step by step, success will follow." },
  { bn: "পরিশ্রম আজকে, বিজয় কালকে।", en: "Work hard today, win tomorrow." },
  { bn: "একটা অধ্যায়, একদিনের জন্য।", en: "One chapter, one day at a time." },
  { bn: "নিয়মিত অধ্যয়নই জেতার চাবিকাঠি।", en: "Consistency is key." },
  { bn: "ভয় পেও না, চেষ্টা করো।", en: "Don’t fear, just try." },
  { bn: "আজ অনুশীলন কর, কাল ঝকঝকে হোক।", en: "Practice today, shine tomorrow." },
  { bn: "চেষ্টা করলে কিছুই অসম্ভব নয়।", en: "Nothing is impossible if you try." },
  { bn: "ছোট পদক্ষেপ, বড় সাফল্য।", en: "Small steps lead to big results." },
  { bn: "পরীক্ষা নয়, প্রস্তুতি গুরুত্বপূর্ণ।", en: "Preparation matters more than exams." },
  { bn: "তোমার সাফল্য তোমার হাতেই।", en: "Push yourself." },
  { bn: "অধ্যয়নই আত্মবিশ্বাসের মূল।", en: "Study builds confidence." },
  { bn: "হাল ছাড়ো না।", en: "Don’t give up." },
  { bn: "একটা চেকলিস্ট সম্পন্ন কর, এক ধাপ এগো।", en: "Complete one checklist, move one step." },
  { bn: "বড় স্বপ্ন দেখো।", en: "Dream big." },
  { bn: "পরিশ্রমের বিকল্প নেই।", en: "No substitute for hard work." },
  { bn: "আজ মনোযোগ দাও, কাল জয় করো।", en: "Focus today, conquer tomorrow." },
  { bn: "ব্যর্থ হও, আবার চেষ্টা করো।", en: "Try again." },
  { bn: "সাফল্য অর্জন করতে হয়।", en: "Success is earned." },
  { bn: "দৃঢ় ইচ্ছাশক্তি সব বাধা দূর করে।", en: "Strong will overcomes obstacles." },
  { bn: "প্রতিটি চেষ্টা গুরুত্বপূর্ণ।", en: "Every effort counts." },
  { bn: "ভয়কে পিছনে ফেলে এগিয়ে যাও।", en: "Leave fear behind and move forward." },
  { bn: "অনুপ্রাণিত থাকো।", en: "Stay motivated." },
  { bn: "কঠের পরিশ্রমের ফল মিষ্টি।", en: "Hard work pays off." },
  { bn: "ধাপে ধাপে, অধ্যায়ে অধ্যায়ে।", en: "Step by step, chapter by chapter." },
  { bn: "আজকে অধ্যয়ন করো, ভবিষ্যত তৈরি করো।", en: "Study today, build your future." },
  { bn: "ভুল হলো শিক্ষার অংশ।", en: "Mistakes are lessons." },
  { bn: "শিখতে থামো না।", en: "Keep learning." },
  { bn: "ধারাবাহিক প্রচেষ্টাই সাফল্য আনে।", en: "Success favors the persistent." },
  { bn: "পরিশ্রমই সফলতার চাবিকাঠি।", en: "Effort is the key to success." },
  { bn: "এখন থামো না।", en: "Don’t stop now." },
  { bn: "আপনার লক্ষ্য মনে রেখো।", en: "Keep your goal in mind." },
  { bn: "ছোট জয়গুলো বড় সাফল্যের দিকে নিয়ে যায়।", en: "Small wins lead to big victories." },
  { bn: "চেষ্টা কর, হেরে যাওয়াও একটি শিক্ষা।", en: "Trying and failing is also learning." },
  { bn: "নিজের উপর বিশ্বাস রাখো।", en: "Believe in yourself." },
  { bn: "সময় অপচয় করো না।", en: "Time is precious." },
  { bn: "প্রস্তুতি আত্মবিশ্বাস দেয়।", en: "Preparation creates confidence." },
  { bn: "একটা অধ্যায় শেষ হলো মানে, এক ধাপ এগো।", en: "One chapter completed is one step ahead." },
  { bn: "কোন শর্টকাট নেই।", en: "No shortcuts." },
  { bn: "হাল ছাড়ো না, আজকের চেষ্টা কালকে ফল দেবে।", en: "Don’t give up, today’s effort pays tomorrow." },
  { bn: "উন্নতি করো, নিখুঁত হওয়ার চেষ্টা নয়।", en: "Progress, not perfection." },
  { bn: "পরিশ্রম করে মানুষ তার স্বপ্ন পূরণ করে।", en: "Hard work makes dreams come true." },
  { bn: "ব্যর্থতা থেকে শিখো।", en: "Learn from failure." },
  { bn: "আজ যা করছ, কাল তার ফল দেখবে।", en: "What you do today, you’ll reap tomorrow." },
  { bn: "নিয়মিত অধ্যয়নই জেতার চাবিকাঠি।", en: "Consistency beats intensity." },
  { bn: "স্বপ্ন দেখো, পরিকল্পনা করো, কাজ করো।", en: "Dream it, plan it, do it." },
  { bn: "ফল নয়, প্রচেষ্টার দিকে মনোযোগ দাও।", en: "Focus on effort, not outcome." },
  { bn: "পরীক্ষা কঠিন হলেও তুমি শক্তিশালী।", en: "Exams are tough, but you are stronger." },
  { bn: "প্রতিটি ছোট পদক্ষেপ গুরুত্বপূর্ণ।", en: "Every small step matters." },
  { bn: "আপনার লক্ষ্য বড় রাখো।", en: "Keep your vision big." },
  { bn: "ইতিবাচক থাকো।", en: "Stay positive." },
  { bn: "ভয়কে এড়িয়ে চেষ্টা করো।", en: "Face your fears and try." },
  { bn: "কোনো অজুহাত নয়।", en: "No excuses." },
  { bn: "অধ্যায় শেষ, আত্মবিশ্বাস বাড়লো।", en: "Chapter complete, confidence increase." },
  { bn: "অন্যের সাথে তুলনা নয়, নিজেকে উন্নত করো।", en: "Don’t compare, compete with yourself." },
  { bn: "পরিশ্রম আজকে, সাফল্য কালকে।", en: "Work today, succeed tomorrow." },
  { bn: "শেখো, পুনরাবৃত্তি করো, অনুশীলন করো।", en: "Learn, revise, practice." },
  { bn: "একটি অধ্যায়ে ফোকাস করো, সব একসাথে নয়।", en: "Focus on one chapter at a time." },
  { bn: "অনুপ্রেরণা ভিতর থেকে আসে।", en: "Motivation is internal." },
  { bn: "চোখ লক্ষ্য থেকে সরবে না।", en: "Keep your eyes on the goal." },
  { bn: "সাফল্য একটি যাত্রা।", en: "Success is a journey." },
  { bn: "পরিশ্রমই তোমার বন্ধু।", en: "Hard work is your friend." },
  { bn: "নিয়মিত অধ্যয়ন অভ্যাস গড়ে তোলে।", en: "Consistency creates habits." },
  { bn: "চ্যালেঞ্জ তোমাকে শক্তিশালী করে।", en: "Challenges make you stronger." },
  { bn: "ভুল ভয় পাও না।", en: "Don’t fear mistakes." },
  { bn: "একটা দিনেই সব নয়, প্রতিদিন অধ্যয়ন করো।", en: "Not everything in a day, study daily." },
  { bn: "থামো না।", en: "Keep pushing." },
  { bn: "সাফল্য প্রস্তুতি ভালোবাসে।", en: "Success loves preparation." },
  { bn: "অনুশীলন নিখুঁত করে।", en: "Practice makes perfect." },
  { bn: "শৃঙ্খলাবদ্ধ থাকো।", en: "Stay disciplined." },
  { bn: "প্রচেষ্টা প্রতিভার চেয়ে বেশি গুরুত্বপূর্ণ।", en: "Your effort matters more than talent." },
  { bn: "পরিশ্রম আজ, আনন্দ কাল।", en: "Effort today, joy tomorrow." },
  { bn: "অপেক্ষা করো না, এখন শুরু করো।", en: "Don’t wait, start now." },
  { bn: "পুনরায় পড়ো, অনুশীলন করো, সফল হও।", en: "Review, practice, succeed." },
  { bn: "প্রতিদিন উন্নতির সুযোগ।", en: "Every day is a chance to improve." },
  { bn: "ফোকাসেড থাকো।", en: "Stay focused." },
  { bn: "পরীক্ষা শুধু চেক, প্রস্তুতি বাস্তব।", en: "Exams are just a test, preparation is real." },
  { bn: "কঠিন দিনগুলো শক্তিশালী ছাত্র তৈরি করে।", en: "Hard days make strong students." },
  { bn: "শেখো, ব্যর্থ হও, বড় হও।", en: "Learn, fail, grow." },
  { bn: "বিশ্বাস করো, পরিশ্রম করো, অর্জন করো।", en: "Believe, work, achieve." },
  { bn: "পরিশ্রম কখনও বৃথা যায় না।", en: "Hard work never goes in vain." },
  { bn: "আজ শুরু করো, কাল নয়।", en: "Start today, not tomorrow." },
  { bn: "ছোট অভ্যাস বড় পরিবর্তন আনে।", en: "Small habits lead to big change." },
  { bn: "আপনার লক্ষ্য মনে রাখো, পথে মনোযোগ রাখো।", en: "Keep your goal in mind, stay focused on the path." },
  { bn: "নিয়মিত অধ্যয়নই তোমার গোপন শক্তি।", en: "Consistency is your secret weapon." },
  { bn: "তোমার অজুহাতের চেয়ে শক্তিশালী হও।", en: "Be stronger than your excuses." },
  { bn: "কোন শর্টকাট নেই।", en: "No shortcut to success." },
  { bn: "আজ অধ্যায়, কাল সাফল্য।", en: "Chapters today, success tomorrow." },
  { bn: "শান্ত থাকো, অধ্যয়ন চালিয়ে যাও।", en: "Keep calm and study on." },
  { bn: "ভুল হলো সাফল্যের সিঁড়ি।", en: "Mistakes are stepping stones." },
  { bn: "ফোকাস করো, পুনরায় পড়ো, পুনরাবৃত্তি করো।", en: "Focus, revise, repeat." },
  { bn: "আপনি যা শিখছো তা শক্তি।", en: "What you learn is power." },
  { bn: "থামো না।", en: "Don’t quit." },
  { bn: "আজকের প্রচেষ্টা কালকে গড়ে।", en: "Today’s effort shapes tomorrow." },
  { bn: "ধৈর্য ধরো, নিয়মিত থাকো।", en: "Be patient, stay consistent." },
  { bn: "পরিশ্রম + পরিকল্পনা = সাফল্য।", en: "Effort + Planning = Success." },
  { bn: "এখন অধ্যয়ন করো, পরে বিশ্রাম নাও।", en: "Study now, relax later." },
  { bn: "চ্যালেঞ্জ হলো সুযোগ।", en: "Challenges are opportunities." },
  { bn: "শিখতে থাকো, বড় হতে থাকো. ", en: "Keep learning, keep growing." },
  { bn: "আজকের অধ্যায়, ভবিষ্যতের সাফল্য।", en: "Today’s chapter, tomorrow’s success." },
  { bn: "তুমি পারবে।", en: "You can do it." }
];

export const SUBJECTS: Subject[] = [
  {
    id: 'bio_1',
    name: 'জীববিজ্ঞান ১ম পত্র (উদ্ভিদবিজ্ঞান)',
    color: '#10b981',
    chapters: [
      { id: 'b1_c1', name: 'কোষ ও এর গঠন' },
      { id: 'b1_c2', name: 'কোষ বিভাজন' },
      { id: 'b1_c3', name: 'কোষ রসায়ন' },
      { id: 'b1_c4', name: 'অণুজীব' },
      { id: 'b1_c5', name: 'শৈবাল ও ছত্রাক' },
      { id: 'b1_c6', name: 'ব্রায়োফাইটা ও টেরিডোফাইটা' },
      { id: 'b1_c7', name: 'নগ্নবীজী ও আবৃতবীজী উদ্ভিদ' },
      { id: 'b1_c8', name: 'টিস্যু ও টিস্যুতন্ত্র' },
      { id: 'b1_c9', name: 'উদ্ভিদ শারীরতত্ত্ব' },
      { id: 'b1_c10', name: 'উদ্ভিদ প্রজনন' },
      { id: 'b1_c11', name: 'জীবপ্রযুক্তি' },
      { id: 'b1_c12', name: 'জীবের পরিবেশ, বিস্তার ও সংরক্ষণ' },
    ],
  },
  {
    id: 'bio_2',
    name: 'জীববিজ্ঞান ২য় পত্র (প্রাণীবিজ্ঞান)',
    color: '#059669',
    chapters: [
      { id: 'b2_c1', name: 'প্রাণীর বিভিন্নতা ও শ্রেণিবিন্যাস' },
      { id: 'b2_c2', name: 'প্রাণীর পরিচিতি' },
      { id: 'b2_c3', name: 'মানব শারীরতত্ত্ব-পরিপাক ও শোষণ' },
      { id: 'b2_c4', name: 'মানব শারীরতত্ত্ব-রক্ত ও সঞ্চালন' },
      { id: 'b2_c5', name: 'মানব শারীরতত্ত্ব-শ্বসন ও শ্বাসক্রিয়া' },
      { id: 'b2_c6', name: 'মানব শারীরতত্ত্ব-বর্জ্য ও নিষ্কাশন' },
      { id: 'b2_c7', name: 'মানব শারীরতত্ত্ব-চলন ও অঙ্গচালনা' },
      { id: 'b2_c8', name: 'মানব শারীরতত্ত্ব-সমন্বয় ও নিয়ন্ত্রণ' },
      { id: 'b2_c9', name: 'মানব জীবনের ধারাবাহিকতা' },
      { id: 'b2_c10', name: 'মানবদেহের প্রতিরক্ষা' },
      { id: 'b2_c11', name: 'জিনতত্ত্ব ও বিবর্তন' },
      { id: 'b2_c12', name: 'প্রাণীর আচরণ' },
    ],
  },
  {
    id: 'chem_1',
    name: 'রসায়ন ১ম পত্র',
    color: '#3b82f6',
    chapters: [
      { id: 'c1_c1', name: 'ল্যাবরেটরির নিরাপদ ব্যবহার' },
      { id: 'c1_c2', name: 'গুণগত রসায়ন' },
      { id: 'c1_c3', name: 'মৌলের পর্যায়বৃত্ত ধর্ম ও রাসায়নিক বন্ধন' },
      { id: 'c1_c4', name: 'রাসায়নিক পরিবর্তন' },
      { id: 'c1_c5', name: 'কর্মমুখী রসায়ন' },
    ],
  },
  {
    id: 'chem_2',
    name: 'রসায়ন ২য় পত্র',
    color: '#2563eb',
    chapters: [
      { id: 'c2_c1', name: 'পরিবেশ রসায়ন' },
      { id: 'c2_c2', name: 'জৈব রসায়ন' },
      { id: 'c2_c3', name: 'পরিমাণগত রসায়ন' },
      { id: 'c2_c4', name: 'তড়িৎ রসায়ন' },
      { id: 'c2_c5', name: 'অর্থনৈতিক রসায়ন' },
    ],
  },
  {
    id: 'phys_1',
    name: 'পদার্থবিজ্ঞান ১ম পত্র',
    color: '#8b5cf6',
    chapters: [
      { id: 'p1_c1', name: 'ভৌতজগৎ ও পরিমাপ' },
      { id: 'p1_c2', name: 'ভেক্টর' },
      { id: 'p1_c3', name: 'গতিবিদ্যা' },
      { id: 'p1_c4', name: 'নিউটনীয় বলবিদ্যা' },
      { id: 'p1_c5', name: 'কাজ, শক্তি ও ক্ষমতা' },
      { id: 'p1_c6', name: 'মহাকর্ষ ও অভিকর্ষ' },
      { id: 'p1_c7', name: 'পদার্থের গাঠনিক ধর্ম' },
      { id: 'p1_c8', name: 'পর্যায়বৃত্ত গতি' },
      { id: 'p1_c9', name: 'তরঙ্গ' },
      { id: 'p1_c10', name: 'আদর্শ গ্যাস ও গ্যাসের গতিতত্ত্ব' },
    ],
  },
  {
    id: 'phys_2',
    name: 'পদার্থবিজ্ঞান ২য় পত্র',
    color: '#7c3aed',
    chapters: [
      { id: 'p2_c1', name: 'তাপগতিবিদ্যা' },
      { id: 'p2_c2', name: 'স্থির তড়িৎ' },
      { id: 'p2_c3', name: 'চল তড়িৎ' },
      { id: 'p2_c4', name: 'তড়িৎ প্রবাহের চৌম্বক ক্রিয়া ও চুম্বকত্ব' },
      { id: 'p2_c5', name: 'তাড়িতচৌম্বকীয় আবেশ ও পরিবর্তী প্রবাহ' },
      { id: 'p2_c6', name: 'জ্যামিতিক আলোকবিজ্ঞান' },
      { id: 'p2_c7', name: 'ভৌত আলোকবিজ্ঞান' },
      { id: 'p2_c8', name: 'আধুনিক পদার্থবিজ্ঞানের সূচনা' },
      { id: 'p2_c9', name: 'পরমাণুর মডেল ও নিউক্লিয়ার পদার্থবিজ্ঞান' },
      { id: 'p2_c10', name: 'সেমিকন্ডাক্টর ও ইলেকট্রনিক্স' },
      { id: 'p2_c11', name: 'জ্যোতির্বিজ্ঞান' },
    ],
  },
  {
    id: 'eng',
    name: 'ইংরেজি',
    color: '#e11d48',
    chapters: [
      { id: 'e_c1', name: 'Parts of Speech (Noun, Pronoun, Adjective)' },
      { id: 'e_c2', name: 'Verb (Right forms of verb, Gerund, Participle, Infinitive)' },
      { id: 'e_c3', name: 'Tense & Sequence of Tense' },
      { id: 'e_c4', name: 'Voice & Narration' },
      { id: 'e_c5', name: 'Preposition' },
      { id: 'e_c6', name: 'Synonyms & Antonyms' },
      { id: 'e_c7', name: 'Idioms and Phrases' },
      { id: 'e_c8', name: 'Correction & Translation' },
      { id: 'e_c9', name: 'Spelling & Vocabulary' },
    ],
  },
  {
    id: 'gk',
    name: 'সাধারণ জ্ঞান',
    color: '#475569',
    chapters: [
      { id: 'gk_c1', name: 'বাংলাদেশের ইতিহাস ও মুক্তিযুদ্ধ (১৯৪৭-১৯৭১)' },
      { id: 'gk_c2', name: 'বঙ্গবন্ধু শেখ মুজিবুর রহমান' },
      { id: 'gk_c3', name: 'বাংলাদেশের ভৌগোলিক অবস্থান ও সীমানা' },
      { id: 'gk_c4', name: 'জাতীয় বিষয়াদি (প্রতীক, পতাকা, সংগীত)' },
      { id: 'gk_c5', name: 'অর্থনীতি, শিল্প ও বাণিজ্য' },
      { id: 'gk_c6', name: 'ক্রীড়া ও সংস্কৃতি' },
      { id: 'gk_c7', name: 'সাম্প্রতিক বাংলাদেশ ও বিশ্ব' },
    ],
  },
];
